// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/homepage-layouts/AppFeed.tsx": () => import("../components/mockups/homepage-layouts/AppFeed.tsx"),
  "./components/mockups/homepage-layouts/CenteredCinematic.tsx": () => import("../components/mockups/homepage-layouts/CenteredCinematic.tsx"),
  "./components/mockups/homepage-layouts/SplitEditorial.tsx": () => import("../components/mockups/homepage-layouts/SplitEditorial.tsx")
};
