// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/instagram-carousel/InstagramCarousel.tsx": () => import("../components/mockups/instagram-carousel/InstagramCarousel.tsx"),
  "./components/mockups/mobile-nav/ExploraSheet.tsx": () => import("../components/mockups/mobile-nav/ExploraSheet.tsx"),
  "./components/mockups/mobile-nav/FloatingBar.tsx": () => import("../components/mockups/mobile-nav/FloatingBar.tsx"),
  "./components/mockups/mobile-nav/TabFAB.tsx": () => import("../components/mockups/mobile-nav/TabFAB.tsx"),
  "./components/mockups/craft-ux/BeerDetail.tsx": () => import("../components/mockups/craft-ux/BeerDetail.tsx"),
  "./components/mockups/craft-ux/BeerDiscovery.tsx": () => import("../components/mockups/craft-ux/BeerDiscovery.tsx"),
  "./components/mockups/craft-ux/CategoryMenu.tsx": () => import("../components/mockups/craft-ux/CategoryMenu.tsx"),
  "./components/mockups/craft-ux/PubPage.tsx": () => import("../components/mockups/craft-ux/PubPage.tsx"),
  "./components/mockups/restyling-2025/BeerDetail.tsx": () => import("../components/mockups/restyling-2025/BeerDetail.tsx"),
  "./components/mockups/restyling-2025/DesignSystem.tsx": () => import("../components/mockups/restyling-2025/DesignSystem.tsx"),
  "./components/mockups/restyling-2025/Explore.tsx": () => import("../components/mockups/restyling-2025/Explore.tsx"),
  "./components/mockups/restyling-2025/HomeFeed.tsx": () => import("../components/mockups/restyling-2025/HomeFeed.tsx"),
  "./components/mockups/restyling-2025/Landing.tsx": () => import("../components/mockups/restyling-2025/Landing.tsx"),
  "./components/mockups/restyling-2025/PubDetail.tsx": () => import("../components/mockups/restyling-2025/PubDetail.tsx")
};
