#!/usr/bin/env bash
# Prepare and verify the Android package and deep-link filters.
#
# Usage:
#   bash scripts/prepare-android-deep-links.sh android to.fermenta.app
#
# The Android project is generated by Capacitor during CI/builds, so this
# script intentionally performs the small amount of native configuration that
# cannot be kept in git (android/ is ignored in this repository).

set -euo pipefail

ANDROID_DIR="${1:-android}"
PACKAGE_NAME="${2:-to.fermenta.app}"
MANIFEST="$ANDROID_DIR/app/src/main/AndroidManifest.xml"
APP_GRADLE="$ANDROID_DIR/app/build.gradle"

if [[ ! "$PACKAGE_NAME" =~ ^[a-zA-Z][a-zA-Z0-9_]*(\.[a-zA-Z][a-zA-Z0-9_]*)+$ ]]; then
  echo "ERRORE: package Android non valido: $PACKAGE_NAME" >&2
  exit 1
fi

if [[ ! -f "$MANIFEST" || ! -f "$APP_GRADLE" ]]; then
  echo "ERRORE: progetto Android incompleto (manifest/build.gradle mancanti)" >&2
  exit 1
fi

echo "── Configuro Android App Links ($PACKAGE_NAME) ──"

# Capacitor scaffolds from capacitor.config.ts (the iOS id is intentionally
# different), therefore force both the Gradle id and namespace for Android.
sed -i -E "s/(applicationId[[:space:]]+)[\"'][^\"']+[\"']/\1\"$PACKAGE_NAME\"/" "$APP_GRADLE"
sed -i -E "s/(namespace[[:space:]]+)[\"'][^\"']+[\"']/\1\"$PACKAGE_NAME\"/" "$APP_GRADLE"

if ! grep -qE "applicationId[[:space:]]+[\"']$PACKAGE_NAME[\"']" "$APP_GRADLE"; then
  echo "ERRORE: impossibile impostare applicationId=$PACKAGE_NAME" >&2
  exit 1
fi

# Move/rewrite the generated MainActivity when Capacitor created it under the
# iOS bundle id. This keeps .MainActivity in the manifest resolvable after the
# Android applicationId/namespace change.
PACKAGE_PATH="${PACKAGE_NAME//./\/}"
TARGET_DIR="$ANDROID_DIR/app/src/main/java/$PACKAGE_PATH"
mkdir -p "$TARGET_DIR"

MAIN_FILE="$(find "$ANDROID_DIR/app/src/main/java" -type f \( -name MainActivity.kt -o -name MainActivity.java \) -print 2>/dev/null | head -1 || true)"
if [[ -z "$MAIN_FILE" ]]; then
  cat > "$TARGET_DIR/MainActivity.kt" <<EOF
package $PACKAGE_NAME

import com.getcapacitor.BridgeActivity

class MainActivity : BridgeActivity()
EOF
  MAIN_FILE="$TARGET_DIR/MainActivity.kt"
  echo "MainActivity generata in $MAIN_FILE"
elif [[ "$MAIN_FILE" != "$TARGET_DIR/"* ]]; then
  MAIN_BASENAME="$(basename "$MAIN_FILE")"
  sed -E "s/^package[[:space:]]+.*/package $PACKAGE_NAME/" \
    "$MAIN_FILE" > "$TARGET_DIR/$MAIN_BASENAME"
  rm -f "$MAIN_FILE"
  MAIN_FILE="$TARGET_DIR/$MAIN_BASENAME"
  echo "MainActivity spostata in $MAIN_FILE"
else
  sed -i -E "s/^package[[:space:]]+.*/package $PACKAGE_NAME/" "$MAIN_FILE"
fi

python3 - "$MANIFEST" <<'PYEOF'
import sys
import xml.etree.ElementTree as ET

manifest_path = sys.argv[1]
android_ns = "http://schemas.android.com/apk/res/android"
ET.register_namespace("android", android_ns)

with open(manifest_path, encoding="utf-8") as handle:
    text = handle.read()

if "FERMENTA_DEEP_LINK" not in text:
    marker = """            <!-- FERMENTA_DEEP_LINK: HTTPS App Links -->
            <intent-filter android:autoVerify="true">
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
                <data android:scheme="https" android:host="fermenta.to" />
            </intent-filter>
            <!-- FERMENTA_DEEP_LINK: custom scheme fallback -->
            <intent-filter>
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
                <data android:scheme="fermentato" />
            </intent-filter>
"""
    # Capacitor's activity declaration can span any number of lines. Match
    # specifically MainActivity and insert before its closing tag, avoiding
    # accidental changes to plugin activities.
    import re
    activity = re.compile(
        r"(?P<open><activity\b[^>]*android:name=[\"'][^\"']*MainActivity[^\"']*[\"'][^>]*>)"
        r"(?P<body>.*?)"
        r"(?P<close></activity>)",
        re.DOTALL,
    )
    match = activity.search(text)
    if not match:
        raise SystemExit("ERRORE: MainActivity non trovata nel manifest")
    text = text[:match.end("body")] + marker + text[match.start("close"):]
    with open(manifest_path, "w", encoding="utf-8") as handle:
        handle.write(text)

try:
    root = ET.parse(manifest_path).getroot()
except ET.ParseError as error:
    raise SystemExit(f"ERRORE: AndroidManifest.xml non valido: {error}")

main_activities = [
    node for node in root.findall(".//activity")
    if str(node.get(f"{{{android_ns}}}name", "")).endswith("MainActivity")
]
if not main_activities:
    raise SystemExit("ERRORE: MainActivity non trovata dopo la patch")

def has_filter(activity, scheme, host=None, auto_verify=None):
    for intent_filter in activity.findall("intent-filter"):
        actions = {
            node.get(f"{{{android_ns}}}name")
            for node in intent_filter.findall("action")
        }
        categories = {
            node.get(f"{{{android_ns}}}name")
            for node in intent_filter.findall("category")
        }
        if "android.intent.action.VIEW" not in actions:
            continue
        if not {
            "android.intent.category.DEFAULT",
            "android.intent.category.BROWSABLE",
        }.issubset(categories):
            continue
        if auto_verify is not None and (
            intent_filter.get(f"{{{android_ns}}}autoVerify") == "true"
        ) != auto_verify:
            continue
        for data in intent_filter.findall("data"):
            if data.get(f"{{{android_ns}}}scheme") != scheme:
                continue
            if host is not None and data.get(f"{{{android_ns}}}host") != host:
                continue
            return True
    return False

activity = main_activities[0]
if not has_filter(activity, "https", "fermenta.to", True):
    raise SystemExit("ERRORE: intent-filter HTTPS autoVerify mancante o errato")
if not has_filter(activity, "fermentato", auto_verify=False):
    raise SystemExit("ERRORE: intent-filter custom scheme fermentato mancante o errato")

print("✅ Intent-filter verificati: https://fermenta.to/* (autoVerify) + fermentato://")
print(f"✅ Android package verificato: {root.get('package', '(gestito da namespace)')}")
PYEOF

echo "✅ Android App Links pronti per $PACKAGE_NAME"